################################################################################
# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
################################################################################

projectionMatrix_3x4:
- 1020.34
- -185.068
- -5.89067
- 293273.0
- 90.3805
- 468.997
- 920.458
- 102354.0
- -0.155839
- -0.873847
- 0.460549
- -1470.32
modelInfo:
  height: 250.0
  radius: 30.0
