################################################################################
# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
################################################################################

projectionMatrix_3x4:
- 1070.94
- 59.032
- 29.8682
- -1078.21
- -55.1826
- 529.847
- 931.399
- -33622.6
- 0.0340113
- -0.867829
- 0.495698
- -1474.38
modelInfo:
  height: 250.0
  radius: 30.0
