################################################################################
# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
################################################################################

projectionMatrix_3x4:
- 997.08
- -452.451
- 4.64029
- -148.328
- 204.954
- 461.626
- 971.492
- -31054.0
- -0.368416
- -0.807159
- 0.461263
- -1400.73
modelInfo:
  height: 250.0
  radius: 30.0
